image:
  - Visual Studio 2017

environment:
  global:
    NAME: glfw
    ASDF_SYSTEM: bodge-glfw
  matrix:
  - platform: x64
    TARGET_ARCH: x86_64
    CFLAGS: -m64
    PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
  - platform: x86
    TARGET_ARCH: i686
    CFLAGS: -m32
    PATH: C:\msys64\mingw32\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-i686-toolchain mingw-w64-i686-cmake

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

install:
  - set APPVEYOR_BUILD_DIR=$(cygpath -u '%APPVEYOR_BUILD_FOLDER%')
  - git submodule update --init --recursive
  - >
    sh -c "
    pacman --needed --noconfirm -S zip unzip base-devel %PACKAGES% &&
    curl -L http://bodge.borodust.org/files/install.sh | sh
    "

build_script:
  - set TARGET_ARTIFACT=lib%NAME%.dll.bodged-%TARGET_ARCH%-windows-%APPVEYOR_REPO_TAG_NAME%
  - set SPEC_ARCHIVE=%TARGET_ARTIFACT%-spec.zip
  - >
    sh -c "
    cd src/lib/
    && cmake -G \"Unix Makefiles\" -DCMAKE_C_FLAGS=%CFLAGS% -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_SHARED_LIBS=ON
    -DLIBRARY_OUTPUT_PATH=$APPVEYOR_BUILD_FOLDER/src/lib/ -DGLFW_BUILD_TESTS=OFF
    -DGLFW_BUILD_DOCS=OFF -DGLFW_INSTALL=OFF -DGLFW_BUILD_EXAMPLES=OFF .
    && make"
  - mv %APPVEYOR_BUILD_FOLDER%\src\lib\lib%NAME%.dll.bodged %APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%
  - >
    sh -c "
    export PATH=$HOME/bin/:$PATH
    && rm -rf %APPVEYOR_BUILD_DIR%/spec/*
    && ln -s %APPVEYOR_BUILD_DIR%/ ~/quicklisp/local-projects/
    && $HOME/bin/lisp %APPVEYOR_BUILD_DIR%/regen-spec.lisp '%ASDF_SYSTEM%' t %TARGET_ARCH%
    && cd ~/quicklisp/local-projects/%ASDF_SYSTEM%/ && zip -r spec.zip spec/
    && mv ~/quicklisp/local-projects/%ASDF_SYSTEM%/spec.zip %APPVEYOR_BUILD_DIR%/
    "
  - mv %APPVEYOR_BUILD_FOLDER%\spec.zip %APPVEYOR_BUILD_FOLDER%\%SPEC_ARCHIVE%

artifacts:
  - path: $(TARGET_ARTIFACT)
    name: target_artifact

  - path: $(SPEC_ARCHIVE)
    name: spec_archive

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact, spec_archive
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
